{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name | default (include "spring-boot.fullname" .) }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.virtualService.hosts }}
        - {{ . | quote }}
        {{- end }}
{{- end }}

{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "spring-boot.fullname" . }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    {{- range .Values.istio.virtualService.gateways }}
    - {{ . | quote }}
    {{- end }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "spring-boot.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
{{- end }}

{{- if and .Values.istio.enabled .Values.istio.mtls }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "spring-boot.fullname" . }}-peer-policy
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spring-boot.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }} 