apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.backup.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
  storageClassName: {{ .Values.backup.storage.storageClassName }} 