groups:
- name: node.rules
  rules:
  - alert: HighNodeCPU
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "Node CPU usage is above 80% for more than 10 minutes (current value: {{ $value }}%)"

  - alert: HighNodeMemory
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Node memory usage is above 90% for more than 10 minutes (current value: {{ $value }}%)"

  - alert: HighNodeDiskUsage
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage on {{ $labels.instance }}"
      description: "Node disk usage is above 85% for more than 10 minutes (current value: {{ $value }}%)"

  - alert: NodeDown
    expr: up{job="kubernetes-nodes"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Node {{ $labels.instance }} is down"
      description: "Node has been down for more than 5 minutes"

- name: kubernetes.rules
  rules:
  - alert: KubernetesPodNotHealthy
    expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Failed|Unknown|Pending"}) > 0
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in {{ $labels.namespace }} is not healthy"
      description: "Pod has been in a non-ready state for more than 15 minutes"

  - alert: KubernetesPodRestartingTooMuch
    expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in {{ $labels.namespace }} is restarting too often"
      description: "Pod has restarted more than 5 times in the last hour"

  - alert: KubernetesPodCrashLooping
    expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} == 1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in {{ $labels.namespace }} is crash looping"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in a CrashLoopBackOff state for more than 10 minutes"

  - alert: KubernetesApiServerDown
    expr: up{job="kubernetes-apiservers"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Kubernetes API server is down"
      description: "API server has been down for more than 5 minutes"

- name: backup.rules
  rules:
  - alert: BackupJobFailed
    expr: kube_job_status_failed{namespace="kube-system", job_name=~"k8s-backup.*"} > 0
    for: 1h
    labels:
      severity: critical
    annotations:
      summary: "Backup job has failed"
      description: "The Kubernetes backup job has failed, backup data may be inconsistent or missing"

  - alert: BackupVolumeAlmostFull
    expr: kubelet_volume_stats_used_bytes{namespace="kube-system", persistentvolumeclaim="backup-pvc"} / kubelet_volume_stats_capacity_bytes{namespace="kube-system", persistentvolumeclaim="backup-pvc"} > 0.85
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "Backup volume is almost full"
      description: "The backup volume is more than 85% full. Older backups may need to be pruned or storage expanded." 