apiVersion: v2
name: monitoring
description: Monitoring stack with Prometheus and Grafana for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: DevOps Team
dependencies:
  - name: prometheus
    version: ~19.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: ~6.50.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: kube-state-metrics
    version: ~4.24.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: ~4.13.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled 