apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-user
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-user
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: prod 